modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId="rainbowcompound" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Create: Rainbow Compound" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/create-rainbow-compound" #optional
logoFile="rainbowcompound.png" #optional
#credits="Thanks to forge, Minecraft, Create and everyone who supported me." #optional
authors="LunaGlaze" #optional
description='''
This is a MOD that may be based on Create.

Added a new and more complicated way to synthesize Chromatic in Create. And added another more advanced Compound.

There is no mandatory theme for this mod, and I welcome the authors of various integration packages to use mods like CrT to modify it to make it more suitable for your integration package.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.rainbowcompound]] #optional
# the modid of the dependency
modId="forge" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory=true #mandatory
# The version range of the dependency
versionRange="[40,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side="BOTH"
# Here's another dependency
[[dependencies.rainbowcompound]]
modId="minecraft"
mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"
[[dependencies.rainbowcompound]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.b,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rainbowcompound]]
    modId="curios"
    mandatory=true
    versionRange="[1.18.2-5.0.6.0,)"
    ordering="NONE"
    side="BOTH"